name: CI

on:
  pull_request:
    branches:
      - main
      - gh/**
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  build-cuda:
    name: Build CUDA
    uses: ./.github/workflows/build-cuda.yml

  build-cpu:
    name: Build CPU
    uses: ./.github/workflows/build-cpu.yml

  test-cpu-python:
    name: Test CPU Python
    needs: build-cpu
    uses: ./.github/workflows/test-cpu-python.yml
    with:
      artifact-name: monarch-cpu-${{ github.sha }}-py3.10

  test-gpu-python:
    name: Test GPU Python
    needs: build-cuda
    uses: ./.github/workflows/test-gpu-python.yml
    with:
      artifact-name: monarch-cuda-${{ github.sha }}-py3.10

  test-gpu-rust:
    name: Test GPU Rust
    needs: build-cuda
    uses: ./.github/workflows/test-gpu-rust.yml
    with:
      artifact-name: monarch-cuda-${{ github.sha }}-py3.10

  build-docker:
    name: Build Docker image
    needs: build-cuda
    uses: ./.github/workflows/build-docker.yml
    with:
      # Docker image requires python 3.12
      artifact-name: monarch-cuda-${{ github.sha }}-py3.12

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    needs: [test-cpu-python, test-gpu-python, test-gpu-rust]
    if: always()
    steps:
      - name: Check all jobs status
        run: |
          if [[ "${{ needs.test-cpu-python.result }}" != "success" ]] ||
             [[ "${{ needs.test-gpu-python.result }}" != "success" ]] ||
             [[ "${{ needs.test-gpu-rust.result }}" != "success" ]]; then
            echo "One or more jobs failed"
            exit 1
          else
            echo "All jobs passed"
          fi
